### ISSUE TITLE
Support default.md fallback

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-dispatch#138]
When requesting `/authors/lars.html`, `dispatch` should not just request `/authors/lars.md`, but also `/authors/default.md`, so that we can create a page that says "this author does not exist".

**Comment by trieloff** [comment]
See https://github.com/davidnuescheler/theblog/issues/3

**Comment by tripodsan** [comment]
I would not serve _wrong_ content. Better: respond with a redirect to `/authors/default.html`

**Comment by tripodsan** [comment]
> See [davidnuescheler/theblog#3](https://github.com/davidnuescheler/theblog/issues/3)

why is this related to issue  #3 ?

**Comment by kptdobe** [comment]
The idea behind davidnuescheler/theblog#3 is that we can request: `/author/a.html`, `/author/b.html`... `/author/z.html` without having to write all corresponding md files but have a generic way to process all of them (like display "Author j does not have a biography yet.").

I would rather fallback to a `*.md`.
I agree with @tripodsan, serving the wrong content is not a good idea and makes thing even more complicated than they are already.

**Comment by kptdobe** [comment]
And supporting a `*.md` would not break backward comp.

**Comment by rofe** [comment]
I'm a bit worried that we could run into trouble with a `*.md` on certain platforms... `default.md` or `index.md` might be the safer choice.

**Comment by rofe** [comment]
I was thinking of another possible approach to this: maybe we should expand on the existing 404 error handling instead of introducing a new convention, and look for a `404.md` in the current folder, then cascade up until we hit the root:
- `/authors/foo.md` > `/authors/404.md` > `/404.md`
- `/products/experience-cloud/analytics.md` > `/products/experience-cloud/404.md` > `/products/404.md` > `/404.md`

**Comment by trieloff** [comment]
@kptdobe I'm downloading Windows right now, to see if `*.md` would be a viable file name there (it is on macOS), but even then it doesn't improve backwards compatibility, it just reduces the risk of collision.

@rofe cascading is hard to do, because you either need to hit all possible 404 pages preemptively (wasted cycles) or things will be slow. Also, the dynamic default is different from a 404: it does not come with an error status code (which we would need to find a way of suppressing) and it is not for missing content. It is for content that is there, just not yet fleshed out.

**Comment by kptdobe** [comment]
Then I do not get the back comp issue. Your change would trigger one more request to `*.md`, if not present, use the next one, 404.html as before. Oder ? And naturally, I assume that one as ever used a `*.md` in his repo which would be the only case where is breaks. But can you request `/*.html` ?

Regarding the use case, there is a difference between supporting a page that says 

1. "this author does not have a biography" (fallback to default.md / *.md inside /authors)
2. "the author X does not have a biography yet". (fallback to default.md / *.md inside /authors but with some dynamicity somewhere)
3. "the author page your requested does not exist" (redirect to default.html inside /authors)
4. "the page you requested does not exists" (fallback to 404.html)

theblog.adobe.com implements 1: see https://theblog.adobe.com/author/bla.

I am with @tripodsan regarding delivering the wrong content but I do not like the redirect because it does not allow us to do 2.

**Comment by trieloff** [comment]
> And naturally, I assume that one as ever used a *.md in his repo which would be the only case where is breaks.

Reading this as "I assume that *no one* ever… which would be the only case where *this* breaks"

Yes, that's the only case where it breaks, but like the tree falling in the woods, when no one is around, I'd still consider this breaking compatibility.

**Comment by kptdobe** [comment]
Waouh... so many typos in one sentence ;) But you read right and thanks for the explanation. I understand and I agree.

**Comment by rofe** [comment]
> But can you request `/*.html` ?

Yes you can. Helix will serve it. But I stand by my statement above regarding `*.md`.

**Comment by rofe** [comment]
> cascading is hard to do

Then we could limit it to the current folder only, with fallback to root?
- `/authors/adobe/foo.md` > `/authors/adobe/404.md` > `/404.md`

**Comment by kptdobe** [comment]
In the end, it is just about being clear on the use case we want to support here.

For the Topics case:
- a redirect to `404.md` or `default.md` forces us to add a md file per topic in the folder.
- a `*.md` (or a `default.md without redirect`) allows us to have only one md file to cover all the topics dynamically (use the name in the url (instead of the *) and maybe compute some content in the `pre.js`).
We do not necessarily want one empty md file per topic, this would be useless.

For the Authors case: we'll need a md file per author to store the picture and bio and the case where the author does not exist does not really matter, it would be a fallback to "something" anyway.

**Comment by trieloff** [comment]
*.md is possible (works on Windows), but feels too weird to me, that’s why I’d like to keep default.md

We can add one more top level fallback, if Alex and Tobi are ok with it.

**Comment by kptdobe** [comment]
I still do not like that we use `default.md` as the fallback, but I googled at little bit and apart from Hugo CMS theme archetype (default.md seems to be a naming convention too), I could not find any evidence that `default.md` is a naming convention for content somewhere. At one point if this becomes an issue, we could still provide a config to change the fallback name.
